server:
  servlet:
    contextPath: /hw
  port: 8081
  tomcat:
    basedir: ./
    accessLog:
      enabled: true
      prefix: access
      pattern: '%h|%l|%u|%t|"%r"|%s|%b|%D| -'

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: hello-world
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhuansun
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379


# mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 实体扫描，多个 package 用逗号或者分号分隔
  typeAliasesPackage: com.zspc.hw.common.entity
  #  typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      # 驼峰下划线转换
      column-underline: true
      # 数据库大写下划线转换
      # capital-mode: true
      # 逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
    # 刷新 mapper
    refresh: false
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    local-cache-scope: statement

